/*
 * LO QUE EL BOT YA TRAE APRENDIDO
 * Decretos que el intérprete local no entendía y que la IA le enseñó (ver aprendiz.js).
 * Cada ejemplo: [texto, { accion, objeto } | { tema, dir }, con conceptos opcionales].
 * Para añadir lo aprendido en una partida: escribe "exportar" en el juego y pega aquí la lista.
 */
(function (RF) {
  'use strict';
  RF.APRENDIDOS = [
    ['que nadie beba soju', {accion: 'PROHIBIR', objeto: 'VICIOS'}],
    ['repartir kimchi en las calles', {accion: 'SUBSIDIAR', objeto: 'COMIDA'}],
    ['darle de comer al pueblo', {accion: 'SUBSIDIAR', objeto: 'COMIDA'}],
    ['meter más pasta en los hospitales', {accion: 'INVERTIR', objeto: 'SALUD'}],
    ['poner más médicos en los pueblos', {accion: 'INVERTIR', objeto: 'SALUD'}],
    ['quitarle la plata a los colegios', {accion: 'RECORTAR', objeto: 'EDUCACION'}],
    ['menos dinero para las escuelas', {accion: 'RECORTAR', objeto: 'EDUCACION'}],
    ['que los periodistas escriban lo que yo diga', {accion: 'CONTROLAR', objeto: 'PRENSA'}],
    ['apagar internet', {accion: 'PROHIBIR', objeto: 'INTERNET'}],
    ['desenchufar la red', {accion: 'PROHIBIR', objeto: 'INTERNET'}],
    ['perseguir a los cristianos', {accion: 'CASTIGAR', objeto: 'RELIGION'}],
    ['más tanques para el ejército', {accion: 'INVERTIR', objeto: 'EJERCITO'}],
    ['pagar el doble a los soldados', {accion: 'SUBSIDIAR', objeto: 'EJERCITO'}],
    ['darle medallas a los generales', {accion: 'SUBSIDIAR', objeto: 'EJERCITO'}],
    ['dejar que la oposición haga mítines', {accion: 'LEGALIZAR', objeto: 'OPOSICION'}],
    ['que las empresas sean del estado', {accion: 'NACIONALIZAR', objeto: 'EMPRESAS'}],
    ['vender las minas a los chinos', {accion: 'PRIVATIZAR', objeto: 'RECURSOS'}],
    ['sacar más carbón de las minas', {accion: 'INVERTIR', objeto: 'CARBON', conceptos: ['carbon_divisas']}],
    ['sube la luz', {accion: 'SUBIR_IMPUESTO', objeto: 'ENERGIA'}],
    ['que haya luz las 24 horas', {accion: 'INVERTIR', objeto: 'ENERGIA'}],
    ['acabar con los apagones', {accion: 'INVERTIR', objeto: 'ENERGIA'}],
    ['echar a los extranjeros', {accion: 'PROHIBIR', objeto: 'EXTRANJEROS'}],
    ['armar al pueblo', {accion: 'LEGALIZAR', objeto: 'ARMAS'}],
    ['que cada casa tenga un fusil', {accion: 'OBLIGAR', objeto: 'ARMAS'}],
    ['requisar las armas', {accion: 'PROHIBIR', objeto: 'ARMAS'}],
    ['declarar la guerra a los narcos', {accion: 'CASTIGAR', objeto: 'NARCO'}],
    ['comerse a los gatos', {accion: 'PROHIBIR', objeto: 'MASCOTAS'}],
    ['quitar las vacaciones', {accion: 'PROHIBIR', objeto: 'CALENDARIO'}],
    ['estatuas mías en cada pueblo', {accion: 'GLORIFICAR', objeto: 'LIDER'}],
    ['que todos lleven mi foto', {accion: 'GLORIFICAR', objeto: 'LIDER'}],
    ['prohibir los vaqueros', {accion: 'PROHIBIR', objeto: 'ROPA'}],
    ['que todos se corten el pelo como yo', {accion: 'OBLIGAR', objeto: 'ROPA'}],
    ['un móvil para cada ciudadano', {accion: 'SUBSIDIAR', objeto: 'TECNOLOGIA', conceptos: ['informacion_contagiosa']}],
    ['plantar árboles en los montes', {accion: 'INVERTIR', objeto: 'AMBIENTE'}],
    ['tractores para los campesinos', {accion: 'INVERTIR', objeto: 'AGRO'}],
    ['fabricar más acero', {accion: 'ENFOCAR', objeto: 'INDUSTRIA'}],
    ['que la economía viva de la pesca', {accion: 'ENFOCAR', objeto: 'AGRO'}],
    ['darle a la maquinita de billetes', {accion: 'CREAR', objeto: 'DINERO', conceptos: ['dinero_sin_respaldo']}],
    ['que los donju paguen más', {accion: 'SUBIR_IMPUESTO', objeto: 'EMPRESAS'}],
    ['perdonar los impuestos a los campesinos', {accion: 'BAJAR_IMPUESTO', objeto: 'AGRO'}],
    ['quitar impuestos a las empresas', {accion: 'BAJAR_IMPUESTO', objeto: 'EMPRESAS'}],
    ['elecciones de verdad', {accion: 'LEGALIZAR', objeto: 'ELECCIONES'}],
    ['cambiar la constitución para ser eterno', {accion: 'CONTROLAR', objeto: 'CONSTITUCION'}],
    ['que los trabajadores cobren más', {accion: 'SUBSIDIAR', objeto: 'TRABAJADORES', conceptos: ['sueldo_sin_produccion']}],
    ['prohibir las huelgas', {accion: 'PROHIBIR', objeto: 'TRABAJADORES'}],
    ['subir el billete del metro', {accion: 'SUBIR_IMPUESTO', objeto: 'TRANSPORTE'}],
    ['un tren bala a Seúl', {tema: 'INFRAESTRUCTURA', dir: 'favor', conceptos: ['obras_publicas']}],
    ['traer arroz de fuera', {tema: 'COMERCIO_EXTERIOR', dir: 'favor', conceptos: ['ventaja_comparativa']}],
    ['aceptar la comida de la ONU', {tema: 'AYUDA_HUMANITARIA', dir: 'favor', conceptos: ['ayuda_fungible']}],
    ['soltar a los presos', {tema: 'AMNISTIA', dir: 'favor', conceptos: ['liberalizar_peligro']}],
    ['echar a la mitad de los funcionarios', {tema: 'BUROCRACIA', dir: 'favor', conceptos: ['paro_oculto']}],
    ['dejar que la gente se vaya del país', {tema: 'EMIGRACION', dir: 'favor', conceptos: ['salida_voz']}],
    ['disparar a los que crucen el río', {tema: 'EMIGRACION', dir: 'contra', conceptos: ['salida_voz']}],
    ['gasolina más cara', {tema: 'COMBUSTIBLE', dir: 'contra', conceptos: ['combustible_cadena']}],
    ['70 días de trabajo sin descanso', {tema: 'CAMPANA_PRODUCCION', dir: 'favor', conceptos: ['campana_choque']}],
    ['pinchar los teléfonos de los generales', {tema: 'VIGILANCIA_ELITE', dir: 'favor', conceptos: ['dilema_dictador']}],
    ['cerrar los mercadillos', {tema: 'MERCADOS', dir: 'contra'}],
    ['probar la bomba', {tema: 'NUCLEAR', dir: 'favor'}],
    ['entregar las bombas atómicas', {tema: 'NUCLEAR', dir: 'contra'}],
    ['cerrar la zona de Rason', {tema: 'ZONA_ESPECIAL', dir: 'contra', conceptos: ['enclave']}],
    ['se acabó el alcohol en todo el país', {accion: 'PROHIBIR', objeto: 'VICIOS'}],
    ['prohibir los perros', {accion: 'PROHIBIR', objeto: 'MASCOTAS'}],
    ['sindicatos libres', {accion: 'LEGALIZAR', objeto: 'TRABAJADORES'}],
    ['prohibir los móviles', {accion: 'PROHIBIR', objeto: 'TECNOLOGIA'}],
    // Enseñados jugando (revisados: la IA marcó la 2ª como "en contra" de la esclavitud)
    ['Prohibir el consumo de drogas en Corea del Norte es solo para exportaciones', {accion: 'ENFOCAR', objeto: 'NARCO', conceptos: ['narcoestado']}],
    ['Fábricas de opio a hasta morir', {tema: 'ESCLAVITUD', dir: 'favor', conceptos: ['narcoestado']}],
    // Aprendidos jugando y revisados en la base de datos del juego
    ['Promover la natalidad', {tema: 'NATALIDAD', dir: 'favor', conceptos: ['natalidad_incentivos']}],
    ['Enviar a a estudiantes a estudiar afuera', {accion: 'INVERTIR', objeto: 'EDUCACION', conceptos: ['estudiar_fuera', 'informacion_contagiosa']}],
    ['Pedir inversión china, abrir economía a china totalmente', {tema: 'COMERCIO_EXTERIOR', dir: 'favor', conceptos: ['dependencia_china', 'captura_privatizacion']}],
    ['Meterle inversión al carbón', {accion: 'INVERTIR', objeto: 'CARBON', conceptos: ['carbon_divisas', 'dependencia_china']}],
    ['la producción agrícola para consuma nacional', {tema: 'EXPORTACIONES', dir: 'contra'}],
    // Huecos encontrados al medir la historia
    ['enviar estudiantes al extranjero', {accion: 'INVERTIR', objeto: 'EDUCACION', conceptos: ['estudiar_fuera']}],
    ['becas para estudiar en China', {accion: 'INVERTIR', objeto: 'EDUCACION', conceptos: ['estudiar_fuera']}],
    ['desmantelar la bomba', {tema: 'NUCLEAR', dir: 'contra'}],
    ['destruir las armas nucleares', {tema: 'NUCLEAR', dir: 'contra'}],
    ['voto para las mujeres', {tema: 'VOTO_MUJERES', dir: 'favor'}],
    ['junta militar', {accion: 'CREAR', objeto: 'JUNTA'}],
    ['que gobiernen los generales', {accion: 'CREAR', objeto: 'JUNTA'}]
  ];
})(globalThis.RF = globalThis.RF || {});
